### ISSUE TITLE
Cannot compile on Ubuntu 22.04.4

### ISSUE THREAD

**Issue by spoofy-zz** [wrljet/hercules-helper#43]
```
  CC       impl.lo
In file included from /usr/lib/gcc/x86_64-linux-gnu/11/include/immintrin.h:41,
                 from /usr/lib/gcc/x86_64-linux-gnu/11/include/x86intrin.h:32,
                 from ../hstdinc.h:108,
                 from ../impl.c:17:
../impl.c: In function ‘is_PCLMULQDQ_available’:
/usr/lib/gcc/x86_64-linux-gnu/11/include/wmmintrin.h:116:1: error: inlining failed in call to ‘always_inline’ ‘_mm_clmulepi64_si128’: target specific option mismatch
  116 | _mm_clmulepi64_si128 (__m128i __X, __m128i __Y, const int __I)
      | ^~~~~~~~~~~~~~~~~~~~
../impl.c:881:17: note: called from here
  881 |         acc.v = _mm_clmulepi64_si128 ( mm1.v, mm2.v, 0);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/11/include/immintrin.h:41,
                 from /usr/lib/gcc/x86_64-linux-gnu/11/include/x86intrin.h:32,
                 from ../hstdinc.h:108,
                 from ../impl.c:17:
/usr/lib/gcc/x86_64-linux-gnu/11/include/wmmintrin.h:116:1: error: inlining failed in call to ‘always_inline’ ‘_mm_clmulepi64_si128’: target specific option mismatch
  116 | _mm_clmulepi64_si128 (__m128i __X, __m128i __Y, const int __I)
      | ^~~~~~~~~~~~~~~~~~~~
../impl.c:881:17: note: called from here
  881 |         acc.v = _mm_clmulepi64_si128 ( mm1.v, mm2.v, 0);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:2639: impl.lo] Error 1
make[2]: Leaving directory '/home/bnovak/git/hercules-helper/build/hyperion/build'
make[1]: *** [Makefile:2689: all-recursive] Error 1
make[1]: Leaving directory '/home/bnovak/git/hercules-helper/build/hyperion/build'
make: *** [Makefile:2007: all] Error 2

```

**Comment by wrljet** [comment]
Bruno,

This is likely going to be an issue for Hercules itself, but can you please zip up the buildall log and post it here on GitHub.
That will answer a lot of questions for me to proceed.

Bill

**Comment by spoofy-zz** [comment]
Here is
[hercules-buildall-2024-08-29.log](https://github.com/user-attachments/files/16803639/hercules-buildall-2024-08-29.log)

**Comment by wrljet** [comment]
Can you also post the output from `lscpu`

Thanks

**Comment by spoofy-zz** [comment]
```
Architecture:             x86_64
  CPU op-mode(s):         32-bit, 64-bit
  Address sizes:          40 bits physical, 48 bits virtual
  Byte Order:             Little Endian
CPU(s):                   1
  On-line CPU(s) list:    0
Vendor ID:                GenuineIntel
  Model name:             Common KVM processor
    CPU family:           15
    Model:                6
    Thread(s) per core:   1
    Core(s) per socket:   1
    Socket(s):            1
    Stepping:             1
    BogoMIPS:             6385.85
    Flags:                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx 
                          fxsr sse sse2 syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx1
                          6 x2apic hypervisor lahf_lm cpuid_fault pti
Virtualization features:  
  Hypervisor vendor:      KVM
  Virtualization type:    full
Caches (sum of all):      
  L1d:                    32 KiB (1 instance)
  L1i:                    32 KiB (1 instance)
  L2:                     4 MiB (1 instance)
  L3:                     16 MiB (1 instance)
NUMA:                     
  NUMA node(s):           1
  NUMA node0 CPU(s):      0
Vulnerabilities:          
  Gather data sampling:   Not affected
  Itlb multihit:          KVM: Mitigation: VMX unsupported
  L1tf:                   Mitigation; PTE Inversion
  Mds:                    Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
  Meltdown:               Mitigation; PTI
  Mmio stale data:        Unknown: No mitigations
  Reg file data sampling: Not affected
  Retbleed:               Not affected
  Spec rstack overflow:   Not affected
  Spec store bypass:      Vulnerable
  Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:             Mitigation; Retpolines; STIBP disabled; RSB filling; PBRSB-eIBRS Not affected; BHI R
                          etpoline
  Srbds:                  Not affected
  Tsx async abort:        Not affected

```

**Comment by wrljet** [comment]
OK, I believe what is going on here, is you're running under KVM which appears to be emulating a Pentium 4.

That CPU is perhaps too old to support the required instructions.
So gcc is complaining about the missing intrinsics.
This may be relatedly to recently added Hercules features.

In any case, I've added a comment to a recently closed related issue over on SDL-Hercules to see what we can do about.

In the mean time, you might try building Aethra instead of SDL-Hercules.  It *might* have somewhat lesser CPU requirements.
User `--flavor=aethra` to try that.

Bill

**Comment by spoofy-zz** [comment]
Good catch.
CPU type changet to "host" in proxmox vm config and now all OK.
Thank you.
